### ISSUE TITLE
Update of HBCI card configuration for FinTan 3.0

### ISSUE THREAD

**Issue by mbehrle** [willuhn/hibiscus.server#5]
To perform the necessary change to FinTan3.0 I downloaded the latest nightly builds for jameica, hibiscus and hibiscus-server. 

I succeeded in updating the configuration of the HBCI configuration for 1822direkt and DKB to FinTan3.0 with the GUI part on my workstation. For the update to FinTan3.0 it is necessary to change the server address in the bank data. This is possible with the GUI part, but I didn't find any possibility to do that on the server part.

Did I miss something or would that be an option to implement also on the server? Otherwise the server seems to be no more usable at least with old cards.

**Comment by mbehrle** [comment]
Ich sehe gerade, dass andere issues in deutsch geschrieben sind:

Um das notwendige Update auf FinTan3.0 durchzuführen, habe ich mir die letzten nightly builds geholt. Das Update hat über die GUI auch geklappt, man muss dazu allerdings die Bankdaten anpassen. Auf dem Hibiscus Payment Server, der auf einer anderen Maschine läuft, ist diese Anpassung nicht möglich (zumindest habe ich nichts gefunden).

Gibt es eine Möglichkeit, diese Anpassung vorzunehmen oder ist der hibiscus server vorerst mit den bestehenden HBCI Karten nicht mehr zu gebrauchen?

**Comment by willuhn** [comment]
Das Aendern der Kartendaten geht im Payment-Server nicht. Du muesstest die Karte also mal an einer Hibiscus Desktop-Installation anschliessen und anschliessend dort die Bankdaten aendern wie im Wiki unter http://www.willuhn.de/wiki/doku.php?id=spk-fints3#chipkarte beschrieben.

Anschliessend musst du die Kartenleser-Konfiguration im Payment-Server loeschen und neu anlegen und dort die HBCI-Version auf FinTS3 stellen. Die Konten und Umsaetze werden beim Loeschen der Kartenleser-Konfiguration nicht geloescht. Allerdings musst du nach dem Neuanlegen der Konfiguration in den Konten die Synchronisierungsoptionen (Umsatzabruf,...) wieder aktivieren.

PS: Die Issue-Funktion hier auf Github ist eigentlich nicht fuer Support gedacht sondern nur fuer Quellcode-relevante Themen. Wende dich besser ans Forum unter http://www.onlinebanking-forum.de/forum/index.php?f=33
Dort lese und schreibe ich auch mit - und da sind auch erheblich mehr User unterwegs, die auch helfen koennen.
