### ISSUE TITLE
Eingabevalidierung BLZ, Kundenkennung

### ISSUE THREAD

**Issue by lenucksi** [willuhn/hibiscus.server#6]
Problem:
- Der Hibiscus-Server fordert trotz mittlerweile entfallenem BLZ/Kontonummerschema für eine Sicherheitsmedium-Konfiguration noch eine BLZ an.
- Ohne werden die eingegebenen Daten nicht gespeichert.
- Bestimmte Banken verwenden die Kundenkennung nicht. Versuch zu speichern ohne Kundenkennung führt zu Reset aller Felder.

Mögliche Lösung:
- Feld weg oder gegen IBAN (arg spezifisch auf ein Konto) ersetzen?
- Das Feld Kundenkennung könnte man optional machen.

**Comment by willuhn** [comment]
Die BLZ wird protokoll-intern in HBCI auch immer noch verwendet. Daher muss sie zumindest fuer den Bankzugang auch nach wie vor noch eingegeben werden.

Wenn eine Bank keine Kundenkennung verwendet, kann dort nochmal die Benutzerkennung eingegeben werden.
